a = input("Enter First Number !")
b = input("Enter second Number !")
sum = float(a)+float(b)
subtraction = int(a)-int(b)
multiplication = int(a)*int(b)
division = int(a)/int(b)
print ('Sum of the Numbers {}' .format(sum))
print('Subtraction of the numbers {}' .format(subtraction))
print('Multiplication of the numbers {}' .format(multiplication))
print('Division of the numbers {} ' .format(division))